# -*- coding: utf-8 -*-
"""project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q7dU2ZudQ8HUtQ6KyoVsNPl7OQvSECcy
"""

students = []

def add_student():
    name = input("Enter student name: ")
    marks = []
    for i in range(5):
        m = float(input(f"Enter marks for subject {i+1}: "))
        marks.append(m)
    total = sum(marks)
    avg = total / 5
    if avg >= 90:
        grade = "A"
    elif avg >= 75:
        grade = "B"
    elif avg >= 60:
        grade = "C"
    elif avg >= 50:
        grade = "D"
    else:
        grade = "F"
    status = "Pass" if avg >= 50 else "Fail"
    students.append({
        "name": name,
        "marks": marks,
        "total": total,
        "avg": avg,
        "grade": grade,
        "status": status
    })
    print(f"\n{name} added successfully!")

def show_all_students():
  for i in students:
    print(f"Name: {i['name']}"),
    print(f"Average: {i['avg']}".2f),
    print(f"Grade: {i['grade']}"),
    print(f"Pass: {i['status']}")
    print("---------------------")

def find_topper():
  topper = students[0]
  for i in students:
    if i["avg"] > topper["avg"]:
      topper = i
  print(f"Topper: {topper['name']} was having higgest average {topper['avg']} in the class")

def class_average():
  Average = 0
  for i in students:
    Average += i['avg']
  total = Average / (len(students))
  print(total)

def show_menu():
    while True:
        print("1. Add student")
        print("2. Show all students")
        print("3. Find topper")
        print("4. Class average")
        print("5. Exit")
        try:
          choice = input("Enter choice: ")
        except:
          print("Something went wrong, try again")
        #choice = input("Enter choice: ")
        if choice == "1":
            add_student()
        elif choice == "2":
            show_all_students()
        elif choice == "3":
            find_topper()
        elif choice == "4":
            class_average()
        elif choice == "5":
            break
        else:
            print("Invalid choice, try again")
show_menu()